channels:
  - conda-forge
dependencies:
  - adlfs
  - build
  - gcsfs
  - ipytree
  - matplotlib
  - mamba
  - notebook
  - sentinelsat
  - pip:
    - --no-binary rasterio rasterio>=1.3a3  # for fsspec support
