channels:
  - defaults
  - conda-forge
dependencies:
  - black = 19.10b0
  - dask
  - flake8
  - isort
  - make
  - mypy
  - numpy >= 1.20.0
  - pytest
  - pytest-cov
  - rioxarray
  - xarray >= 0.17.0
  - xmlschema
