channels:
  - conda-forge
dependencies:
  - black = 21.12b0
  - dask
  - flake8
  - fsspec
  - isort
  - make
  - mdformat
  - mypy
  - netcdf4
  - nomkl
  - numpy >= 1.22.0
  - pip
  - pytest
  - pytest-cov
  - rasterio >= 1.2.4
  - rioxarray
  - types-setuptools
  - xarray >= 0.20.2
  - xmlschema
  - zarr
  - pip:
    - mdformat-gfm
