channels:
- conda-forge
dependencies:
- dask
- fsspec
- make
- mypy
- netcdf4
- nomkl
- numpy >= 1.22.0
- pytest
- pytest-cov
- rasterio >= 1.3.0
- rioxarray
- shapely
- types-setuptools
- xarray >= 2022.6.0
- xmlschema
- zarr
