name: on-push

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ubuntu-latest-3.8
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        activate-environment: ubuntu-latest-3.8
        auto-update-conda: false
        python-version: 3.8
        use-only-tar-bz2: true
    - name: Install conda dependencies
      run: |
        mamba env update -f environment-ci.yml
        python -m pip install --no-deps https://github.com/pydata/xarray/archive/master.zip  # to enable plugins
    - name: Install xarray-sentinel
      run: |
        python -m pip install --no-deps -e .
    - name: Run unit tests
      run: |
        make unit-test COV_REPORT=xml
    - name: Run doc tests
      run: |
        make doc-test
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v1

  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ubuntu-latest-3.8
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        activate-environment: ubuntu-latest-3.8
        auto-update-conda: false
        python-version: 3.8
        use-only-tar-bz2: true
    - name: Install conda dependencies
      run: |
        mamba env update -f environment-ci.yml
        python -m pip install --no-deps https://github.com/pydata/xarray/archive/master.zip  # to enable plugins
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Type check with mypy
      run: |
        mypy --strict .

  code-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check code style with black
      run: |
        $CONDA/bin/conda install black
        $CONDA/bin/black --check .
    - name: Check code style with isort
      run: |
        $CONDA/bin/conda install isort
        $CONDA/bin/isort --check .

  distribution:
    runs-on: ubuntu-latest
    needs: [unit-tests, code-quality, code-style]

    steps:
    - uses: actions/checkout@v2
    - name: Build distributions
      run: |
        $CONDA/bin/conda install pip setuptools>=42 wheel setuptools_scm[toml]>=3.4 setuptools_scm_git_archive
        $CONDA/bin/python setup.py sdist bdist_wheel
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
